import type { Metadata } from "next";
import "./styles/globals.scss";
import FontProvider from "./components/FontProvider";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <FontProvider />
      </head>
      <body suppressHydrationWarning className="antialiased">
        <div className="nt-admin-layout flex">
          <Sidebar />
          <div className="nt-admin-main-body">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
