import type { Metadata } from "next";
import "./styles/globals.scss";
import FontProvider from "@/components/FontProvider";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { Providers } from '@/app/providers';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <FontProvider />
      </head>
      <body suppressHydrationWarning className="antialiased">
        <Providers>
          <div className="flex h-screen w-full overflow-hidden">
            <Sidebar />
            <div className="flex flex-col flex-1 overflow-hidden">
              <Header />
              <main id="nt-main-content" className="flex-1 overflow-y-auto bg-white dark:bg-gray-900">
                {children}
              </main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
